# Analyze Garmin data prepocess it & export to blender for 3D vizualization

## Sources:
- [Analysis of Running Activities from Garmin Watch Using Python](https://towardsdatascience.com/analysis-of-runing-activities-from-garmin-watch-using-python-99609f83314e)

## Import modules

In [1]:
# import internal modules
# from typing import List, Set, Dict, TypedDict, Tuple, Optional, Union
from pathlib import Path

# import 3rd-party modules
import pandas as pd
import numpy as np

# import local modules

## Define functions

In [145]:
# Create Function to explore the dataframes
def explore(df: pd.DataFrame) -> None:
    """
    Function to print general information about the dataframe
    """
    print("********** 1. General info of data **********")
    print(df.info())
    
    print("\n********** 2. Shape of data **********")
    print(f"Number of rows: {len(df)}")
    print(f"Number of columns: {len(df.columns)}")
    
    print("\n********** 3. Number of missing values per column **********")
    print(df.isnull().sum())
    
    print("\n********** 4. Number of duplicated values **********")
    print(df.duplicated().sum())
    
    print("\n********** 5. Number of unique values per column (NaN non included) **********")
    print(df.nunique())
    
    print("\n********** 6. Statistical info of each column **********")
    # print(df.describe(include='all').T)
    return df.describe(include='all', datetime_is_numeric=True).T

def convert_strings_to_duration(str_series):
    """
    Function to convert series of strings to durations; workaround when multiple formats in series
    """
    return pd.to_timedelta(pd.to_datetime(str_series).dt.strftime("%H:%M:%S.%f"))

def convert_durations_to_minutes(durations_series):
    # durations_series.dt.hour*60 + durations_series.dt.minute + durations_series.dt.second/60
    return durations_series.dt.total_seconds()/60

## Read data

In [153]:
# set csv path
football_activities_df_path = Path("assets/data/garmin_data/football_1_year.csv")

# read csv into dataframe
football_activities_df = pd.read_csv(football_activities_df_path, parse_dates=True)

## Explore data (Exploratory data analysis)

In [10]:
football_activities_df.head()

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Min Temp,Surface Interval,Decompression,Best Lap Time,Number of Laps,Max Temp,Moving Time,Elapsed Time,Min Elevation,Max Elevation
0,Other,2022-08-07 13:49:30,False,Grimbergen Football,8.90,"1,381",02:45:10,140,192,5.0,...,0.0,0:00,No,11:37.86.7,9,0.0,01:49:59,02:45:10,40,42
1,Other,2022-07-31 16:41:23,False,Grimbergen Football,0.62,375,00:30:13,152,185,3.3,...,0.0,0:00,No,30:13.30.7,1,0.0,00:13:03,00:30:13,40,42
2,Other,2022-07-31 14:20:23,False,Grimbergen Football,6.71,775,01:39:29,129,172,3.0,...,0.0,0:00,No,12:10.61.4,7,0.0,01:22:37,01:39:30,40,44
3,Other,2022-07-24 14:43:01,False,Grimbergen Football,4.96,854,01:32:10,137,180,3.4,...,0.0,0:00,No,11:03.70.5,5,0.0,01:07:09,01:49:56,40,45
4,Other,2022-07-17 13:53:02,False,Grimbergen Football,9.09,"1,479",02:22:50,150,195,5.0,...,0.0,0:00,No,04:52.04.1,10,0.0,01:52:40,02:23:16,40,45

In [11]:
explore(football_activities_df)

********** 1. General info of data **********
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Activity Type             40 non-null     object
 1   Date                      40 non-null     object
 2   Favorite                  40 non-null     bool
 3   Title                     40 non-null     object
 4   Distance                  40 non-null     float64
 5   Calories                  40 non-null     object
 6   Time                      40 non-null     object
 7   Avg HR                    40 non-null     int64
 8   Max HR                    40 non-null     int64
 9   Aerobic TE                40 non-null     object
 10  Avg Run Cadence           40 non-null     object
 11  Max Run Cadence           40 non-null     object
 12  Avg Speed                 40 non-null     object
 13  Max Speed                 40 non-null     object
 14  Total Ascent              40 non-null     object
 15  Total Descent             40 non-null     object
 16  Avg Stride Length         40 non-null     float64
 17  Avg Vertical Ratio        40 non-null     float64
 18  Avg Vertical Oscillation  40 non-null     float64
 19  Avg Ground Contact Time   40 non-null     int64
 20  Avg Bike Cadence          40 non-null     int64
 21  Max Bike Cadence          40 non-null     int64
 22  Training Stress Score®    40 non-null     float64
 23  Avg Power                 40 non-null     int64
 24  Max Power                 40 non-null     int64
 25  Grit                      40 non-null     float64
 26  Flow                      40 non-null     float64
 27  Avg. Swolf                40 non-null     int64
 28  Avg Stroke Rate           40 non-null     int64
 29  Total Reps                40 non-null     int64
 30  Dive Time                 40 non-null     object
 31  Min Temp                  40 non-null     float64
 32  Surface Interval          40 non-null     object
 33  Decompression             40 non-null     object
 34  Best Lap Time             40 non-null     object
 35  Number of Laps            40 non-null     int64
 36  Max Temp                  40 non-null     float64
 37  Moving Time               40 non-null     object
 38  Elapsed Time              40 non-null     object
 39  Min Elevation             40 non-null     object
 40  Max Elevation             40 non-null     object
dtypes: bool(1), float64(9), int64(11), object(20)
memory usage: 12.7+ KB
None

********** 2. Shape of data **********
Number of rows: 40
Number of columns: 41

********** 3. Number of missing values per column **********
Activity Type               0
Date                        0
Favorite                    0
Title                       0
Distance                    0
Calories                    0
Time                        0
Avg HR                      0
Max HR                      0
Aerobic TE                  0
Avg Run Cadence             0
Max Run Cadence             0
Avg Speed                   0
Max Speed                   0
Total Ascent                0
Total Descent               0
Avg Stride Length           0
Avg Vertical Ratio          0
Avg Vertical Oscillation    0
Avg Ground Contact Time     0
Avg Bike Cadence            0
Max Bike Cadence            0
Training Stress Score®      0
Avg Power                   0
Max Power                   0
Grit                        0
Flow                        0
Avg. Swolf                  0
Avg Stroke Rate             0
Total Reps                  0
Dive Time                   0
Min Temp                    0
Surface Interval            0
Decompression               0
Best Lap Time               0
Number of Laps              0
Max Temp                    0
Moving Time                 0
Elapsed Time                0
Min Elevation               0
Max Elevation               0
dtype: int64

********** 4. Number of duplicated values **********
0

********** 5. Number of unique values per column (NaN non included) **********
Activity Type                1
Date                        40
Favorite                     1
Title                        5
Distance                    38
Calories                    40
Time                        40
Avg HR                      29
Max HR                      26
Aerobic TE                  24
Avg Run Cadence             26
Max Run Cadence             21
Avg Speed                   28
Max Speed                   36
Total Ascent                17
Total Descent               17
Avg Stride Length           25
Avg Vertical Ratio           1
Avg Vertical Oscillation     1
Avg Ground Contact Time      1
Avg Bike Cadence             1
Max Bike Cadence             1
Training Stress Score®       1
Avg Power                    1
Max Power                    1
Grit                         1
Flow                         1
Avg. Swolf                   1
Avg Stroke Rate              1
Total Reps                   1
Dive Time                    1
Min Temp                     1
Surface Interval             1
Decompression                1
Best Lap Time               40
Number of Laps              12
Max Temp                     1
Moving Time                 31
Elapsed Time                40
Min Elevation               14
Max Elevation               17
dtype: int64

********** 6. Statistical info of each column **********

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Activity Type,40,1,Other,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date,40,40,2022-07-10 14:36:44,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Favorite,40,1,False,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Title,40,5,Grimbergen Football,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Distance,40.0,NaN,NaN,NaN,4.45575,3.036394,0.0,1.65,4.72,6.6275,10.14
Calories,40,40,260,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time,40,40,00:30:13,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Avg HR,40.0,NaN,NaN,NaN,139.125,13.291963,113.0,130.75,140.5,150.5,161.0
Max HR,40.0,NaN,NaN,NaN,173.65,20.041687,134.0,161.75,181.0,190.5,199.0
Aerobic TE,40,24,5.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Avg Run Cadence,40,26,63,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Max Run Cadence,40,21,232,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Avg Speed,40,28,3.9,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Max Speed,40,36,23.6,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Ascent,40,17,--,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Descent,40,17,--,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Avg Stride Length,40.0,NaN,NaN,NaN,0.9615,0.285725,0.0,0.9725,1.025,1.11,1.38
Avg Vertical Ratio,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Avg Vertical Oscillation,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Avg Ground Contact Time,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Avg Bike Cadence,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Max Bike Cadence,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Training Stress Score®,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Avg Power,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Max Power,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grit,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Flow,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Avg. Swolf,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Avg Stroke Rate,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Total Reps,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Dive Time,40,1,0:00,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Min Temp,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Surface Interval,40,1,0:00,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Decompression,40,1,No,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Best Lap Time,40,40,04:30.85.8,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number of Laps,40.0,NaN,NaN,NaN,5.275,3.088336,1.0,2.75,5.0,7.0,13.0
Max Temp,40.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Moving Time,40,31,00:00:00,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Elapsed Time,40,40,00:30:13,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Min Elevation,40,14,40,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Max Elevation,40,17,45,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Clean data

In [154]:
# select columns to keep
selected_cols = [
    "Date",
    "Title",
    "Distance",
    "Calories",	"Time", "Avg HR", "Max HR", "Aerobic TE", "Avg Run Cadence",
    "Max Run Cadence", "Avg Speed", "Max Speed", "Total Ascent", "Total Descent", "Avg Stride Length", 
    "Best Lap Time", "Number of Laps", "Max Temp", "Moving Time", "Elapsed Time", "Min Elevation", "Max Elevation"
    ]

football_activities_df = football_activities_df[selected_cols]

### ToDo: find better solution to parse duration strings
ideas: 
- coerce error to convert error to nan and then fill na with other format
- consolidate strings in 1 format

In [155]:
# convert concerned cols to datetime & duration time
football_activities_df['Date'] = pd.to_datetime(football_activities_df['Date'])
football_activities_df['Time'] = convert_strings_to_duration(football_activities_df['Time'])
football_activities_df['Elapsed Time'] = convert_strings_to_duration(football_activities_df['Elapsed Time'])
football_activities_df['Best Lap Time'] = football_activities_df['Best Lap Time'].apply(lambda x: f"00:{x}" if x.count(":") == 1 else x) # need to add hh:
football_activities_df['Best Lap Time'] = pd.to_timedelta(football_activities_df['Best Lap Time'])
football_activities_df['Moving Time'] = convert_strings_to_duration(football_activities_df['Moving Time'])

# convert durations cols to number of minutes
duration_cols = football_activities_df.select_dtypes(include=["timedelta64[ns]"]).columns

for duration_col in duration_cols:
    football_activities_df[duration_col] = convert_durations_to_minutes(football_activities_df[duration_col])

In [161]:
# replace dummy value "--" by nan
football_activities_df.replace({'--':np.nan}, inplace=True)

# remove comma (to indicate thousands)
football_activities_df["Calories"] = football_activities_df["Calories"].str.replace(',', "")

In [178]:
# convert object cols to float
## select only object cols
object_cols = football_activities_df.select_dtypes(include='object').columns.to_list()

## remove title from object cols
object_cols.remove("Title")

## convert object cols to float
football_activities_df[object_cols] = football_activities_df[object_cols].astype("float")

## inspect cols info
football_activities_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               40 non-null     datetime64[ns]
 1   Title              40 non-null     object
 2   Distance           40 non-null     float64
 3   Calories           39 non-null     float64
 4   Time               40 non-null     float64
 5   Avg HR             40 non-null     int64
 6   Max HR             40 non-null     int64
 7   Aerobic TE         39 non-null     float64
 8   Avg Run Cadence    39 non-null     float64
 9   Max Run Cadence    39 non-null     float64
 10  Avg Speed          39 non-null     float64
 11  Max Speed          39 non-null     float64
 12  Total Ascent       32 non-null     float64
 13  Total Descent      31 non-null     float64
 14  Avg Stride Length  40 non-null     float64
 15  Best Lap Time      40 non-null     float64
 16  Number of Laps     40 non-null     int64
 17  Max Temp           40 non-null     float64
 18  Moving Time        40 non-null     float64
 19  Elapsed Time       40 non-null     float64
 20  Min Elevation      39 non-null     float64
 21  Max Elevation      39 non-null     float64
dtypes: datetime64[ns](1), float64(17), int64(3), object(1)
memory usage: 7.0+ KB

In [180]:
football_activities_df

,Date,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,Avg Run Cadence,Max Run Cadence,...,Total Ascent,Total Descent,Avg Stride Length,Best Lap Time,Number of Laps,Max Temp,Moving Time,Elapsed Time,Min Elevation,Max Elevation
0,2022-08-07 13:49:30,Grimbergen Football,8.90,1381.0,165.166667,140,192,5.0,50.0,232.0,...,1.0,1.0,1.02,11.631117,9,0.0,109.983333,165.166667,40.0,42.0
1,2022-07-31 16:41:23,Grimbergen Football,0.62,375.0,30.216667,152,185,3.3,27.0,232.0,...,NaN,NaN,0.75,30.221783,1,0.0,13.050000,30.216667,40.0,42.0
2,2022-07-31 14:20:23,Grimbergen Football,6.71,775.0,99.483333,129,172,3.0,64.0,248.0,...,4.0,5.0,1.07,12.176900,7,0.0,82.616667,99.500000,40.0,44.0
3,2022-07-24 14:43:01,Grimbergen Football,4.96,854.0,92.166667,137,180,3.4,54.0,232.0,...,9.0,9.0,0.98,11.061750,5,0.0,67.150000,109.933333,40.0,45.0
4,2022-07-17 13:53:02,Grimbergen Football,9.09,1479.0,142.833333,150,195,5.0,67.0,248.0,...,20.0,18.0,0.94,4.867350,10,0.0,112.666667,143.266667,40.0,45.0
5,2022-07-10 14:36:44,Grimbergen Football,3.92,566.0,60.550000,134,165,3.0,69.0,218.0,...,10.0,10.0,0.94,14.148567,4,0.0,50.800000,60.550000,40.0,45.0
6,2022-07-03 13:53:02,Grimbergen Football,7.04,1380.0,123.733333,154,193,5.0,54.0,237.0,...,1.0,0.0,1.01,4.826667,8,0.0,89.916667,123.816667,39.0,40.0
7,2022-06-12 15:00:00,Grimbergen Football,3.03,509.0,46.616667,155,198,4.2,65.0,224.0,...,7.0,10.0,1.00,0.061567,5,0.0,35.950000,46.616667,40.0,45.0
8,2022-06-12 13:55:41,Grimbergen Football,4.48,658.0,63.800000,145,192,3.9,65.0,220.0,...,7.0,7.0,1.07,9.890883,5,0.0,52.633333,63.800000,40.0,45.0
9,2022-06-09 12:23:53,Schaarbeek Football,2.39,358.0,40.033333,132,180,3.1,64.0,242.0,...,38.0,5.0,0.98,11.074117,3,0.0,30.133333,40.033333,76.0,109.0
10,2022-06-05 14:34:22,Grimbergen Football,4.23,420.0,63.216667,119,145,2.0,61.0,242.0,...,1.0,1.0,1.11,6.714133,5,0.0,48.783333,63.216667,40.0,43.0
11,2022-06-02 12:21:06,Schaarbeek Football,2.13,260.0,41.516667,113,141,1.2,60.0,227.0,...,10.0,3.0,0.83,8.857883,3,0.0,31.250000,41.516667,82.0,91.0
12,2022-05-01 16:35:42,Grimbergen Football,6.42,866.0,102.150000,132,192,3.3,64.0,242.0,...,11.0,9.0,0.95,7.641883,7,0.0,64.316667,102.150000,40.0,45.0
13,2022-04-24 16:48:41,Ukkel Football,8.96,1444.0,143.316667,149,196,5.0,63.0,242.0,...,30.0,36.0,0.98,10.588967,9,0.0,97.100000,144.416667,66.0,79.0
14,2022-03-13 14:45:26,Grimbergen Football,5.37,586.0,62.016667,141,170,3.2,80.0,232.0,...,1.0,1.0,1.09,6.364533,6,0.0,51.966667,62.050000,39.0,41.0
15,2022-03-06 15:42:24,Grimbergen Football,1.68,174.0,15.766667,141,158,2.3,106.0,207.0,...,0.0,NaN,1.01,6.627467,2,0.0,15.083333,15.766667,39.0,40.0
16,2022-02-20 14:33:09,Grimbergen Football,6.17,581.0,88.100000,123,155,2.5,68.0,240.0,...,8.0,7.0,1.03,4.514300,7,0.0,65.133333,88.100000,40.0,45.0
17,2021-11-21 14:20:29,Grimbergen Football,3.07,279.0,38.716667,121,142,1.9,78.0,219.0,...,1.0,1.0,1.01,3.147500,4,0.0,34.300000,38.716667,40.0,43.0
18,2021-11-14 13:43:00,Grimbergen Football,10.00,1065.0,120.366667,138,185,3.8,79.0,232.0,...,NaN,NaN,1.07,0.068867,11,0.0,108.650000,120.366667,44.0,45.0
19,2021-11-07 13:22:19,Grimbergen Football,7.31,831.0,79.483333,154,182,4.9,79.0,232.0,...,2.0,2.0,1.16,3.976117,8,0.0,73.950000,109.516667,40.0,43.0
20,2021-10-31 13:22:50,Grimbergen Football,6.62,731.0,97.883333,131,163,3.0,72.0,252.0,...,3.0,17.0,1.07,8.545950,8,0.0,79.316667,97.883333,36.0,53.0
21,2021-10-17 15:16:03,Grimbergen Football,1.56,383.0,56.700000,119,144,2.1,58.0,239.0,...,0.0,NaN,0.56,12.381717,2,0.0,20.466667,56.700000,39.0,40.0
22,2021-10-10 15:31:12,Grimbergen Football,0.60,93.0,9.245000,135,165,1.8,58.0,206.0,...,NaN,NaN,1.12,9.245300,1,0.0,7.316667,9.245000,40.0,43.0
23,2021-09-26 14:24:15,Grimbergen Football,5.52,971.0,84.683333,155,188,4.7,59.0,248.0,...,6.0,6.0,1.10,9.511917,6,0.0,69.683333,84.683333,40.0,44.0
24,2021-09-19 14:01:22,Grimbergen Football,5.70,754.0,75.750000,147,188,3.8,67.0,239.0,...,6.0,5.0,1.13,4.790017,7,0.0,66.450000,81.066667,40.0,44.0
25,2021-08-29 14:41:32,Grimbergen Football,3.35,312.0,54.316667,113,138,1.2,59.0,232.0,...,1.0,1.0,1.05,8.622083,4,0.0,0.000000,54.316667,39.0,41.0
26,2021-08-28 15:32:51,Jette Football,0.56,54.0,6.250000,123,154,0.6,65.0,205.0,...,NaN,NaN,1.38,6.249883,1,0.0,0.000000,6.250000,49.0,52.0
27,2021-08-28 14:24:19,Jette Football,1.68,216.0,23.766667,130,165,2.1,63.0,232.0,...,1.0,1.0,1.11,11.460850,2,0.0,0.000000,23.766667,53.0,55.0
28,2021-08-28 12:14:25,Jette Football,0.93,125.0,10.966667,144,165,2.1,71.0,227.0,...,NaN,1.0,1.18,10.965317,1,0.0,0.000000,10.966667,48.0,51.0
29,2021-08-25 22:09:17,Football,0.00,751.0,64.350000,155,192,4.9,58.0,242.0,...,NaN,NaN,0.00,32.125750,2,0.0,0.000000,64.350000,NaN,NaN
30,2021-08-22 13:50:03,Grimbergen Football,10.14,974.0,114.966667,136,163,3.4,78.0,228.0,...,9.0,7.0,1.14,0.027817,13,0.0,0.000000,125.850000,40.0,45.0
31,2021-08-15 13:42:41,Grimbergen Football,6.65,846.0,72.983333,161,199,5.0,86.0,235.0,...,4.0,8.0,1.05,9.743167,7,0.0,0.000000,98.033333,40.0,46.0
32,2021-08-08 15:30:25,Grimbergen Football,0.27,32.0,3.586667,123,137,0.4,77.0,191.0,...,NaN,NaN,0.99,3.587117,1,0.0,0.000000,3.586667,40.0,40.0
33,2021-08-08 13:24:47,Grimbergen Football,1.46,808.0,78.100000,145,188,3.8,82.0,232.0,...,141.0,140.0,0.26,3.403100,3,0.0,0.000000,91.850000,40.0,111.0
34,2021-07-25 13:26:22,Grimbergen Football,8.32,990.0,99.516667,146,187,4.0,73.0,245.0,...,2.0,2.0,1.16,5.056350,9,0.0,0.000000,115.350000,46.0,48.0
35,2021-07-18 13:52:59,Grimbergen Football,5.71,794.0,68.750000,155,187,4.6,75.0,242.0,...,4.0,3.0,1.11,9.300383,6,0.0,62.866667,92.883333,40.0,45.0
36,2021-07-11 14:27:23,Grimbergen Football,5.01,757.0,67.633333,160,190,5.0,74.0,245.0,...,10.0,4.0,1.01,0.010417,7,0.0,62.983333,67.633333,38.0,45.0
37,2021-07-11 14:02:51,Grimbergen Football,1.09,246.0,20.183333,153,196,3.4,63.0,238.0,...,13.0,13.0,0.88,7.757933,2,0.0,11.083333,20.183333,35.0,41.0
38,2021-07-04 15:51:38,Grimbergen Football,0.00,NaN,0.088333,133,134,NaN,NaN,NaN,...,NaN,NaN,0.00,0.013333,3,0.0,0.063333,0.088333,44.0,44.0
39,2021-07-04 14:24:02,Grimbergen Football,6.58,719.0,72.183333,142,185,3.5,79.0,242.0,...,4.0,5.0,1.16,6.449733,7,0.0,67.883333,83.800000,40.0,44.0